# NETFLIX NLP - DATA MODELING






## Import Libraries

In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import datetime

%matplotlib inline


/Users/tddagdas/opt/anaconda3/envs/Main/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
#Load the aggregate information data
df = pd.read_csv('netflix_titles.csv')

In [3]:
#Number of rows and columns
num_rows, num_columns = df.shape
print('#columns: ', num_columns)
print('#rows: ', num_rows)


#columns:  12
#rows:  7787


In [4]:
#First few rows of the data
df.head()

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...

In [5]:
df1 = pd.read_csv('title_ratings.csv')
df1.head()

tconst  averageRating  numVotes
0  tt0000001            5.7      1775
1  tt0000002            6.0       227
2  tt0000003            6.5      1532
3  tt0000004            6.1       147
4  tt0000005            6.2      2351

In [6]:
df2 = pd.read_csv('title_names.csv')
df2.head()

/Users/tddagdas/opt/anaconda3/envs/Main/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short          Pauvre Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  
0        0      1894      \N              1         Documentary,Short  
1        0      1892      \N              5           Animation,Short  
2        0      1892      \N              4  Animation,Comedy,Romance  
3        0      1892      \N             12           Animation,Short  
4        0      1893      \N              1              Comedy,Short

In [7]:
df3 = df2.merge(df1, on='tconst', how='left')#.query('num_events==num_events')
df3.head()

tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short          Pauvre Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  \
0        0      1894      \N              1         Documentary,Short   
1        0      1892      \N              5           Animation,Short   
2        0      1892      \N              4  Animation,Comedy,Romance   
3        0      1892      \N             12           Animation,Short   
4        0      1893      \N              1              Comedy,Short   

   averageRating  numVotes  
0            5.7    1775.0  
1            6.0     227.0  
2            6.5    1532.0  
3            6.1     147.0  
4            6.2    2351.0

In [8]:
df3.rename(columns={'primaryTitle': 'title'}, inplace=True)

In [9]:
df4 = df3.merge(df, on='title', how='left')#.query('num_events==num_events')
df4.head()

tconst titleType                   title           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short          Pauvre Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  \
0        0      1894      \N              1         Documentary,Short   
1        0      1892      \N              5           Animation,Short   
2        0      1892      \N              4  Animation,Comedy,Romance   
3        0      1892      \N             12           Animation,Short   
4        0      1893      \N              1              Comedy,Short   

   averageRating  ...  type director cast country date_added release_year  \
0            5.7  ...   NaN      NaN  NaN     NaN        NaN          NaN   
1            6.0  ...   NaN      NaN  NaN     NaN        NaN          NaN   
2            6.5  ...   NaN      NaN  NaN     NaN        NaN          NaN   
3            6.1  ...   NaN      NaN  NaN     NaN        NaN          NaN   
4            6.2  ...   NaN      NaN  NaN     NaN        NaN          NaN   

  rating  duration listed_in description  
0    NaN       NaN       NaN         NaN  
1    NaN       NaN       NaN         NaN  
2    NaN       NaN       NaN         NaN  
3    NaN       NaN       NaN         NaN  
4    NaN       NaN       NaN         NaN  

[5 rows x 22 columns]

In [10]:
df4.columns

Index(['tconst', 'titleType', 'title', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
       'show_id', 'type', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [11]:
df4.drop(columns=['titleType', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genres','numVotes',
       'show_id', 'type', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration'], inplace = True)

In [12]:
df4.head()

tconst                   title  averageRating listed_in description
0  tt0000001              Carmencita            5.7       NaN         NaN
1  tt0000002  Le clown et ses chiens            6.0       NaN         NaN
2  tt0000003          Pauvre Pierrot            6.5       NaN         NaN
3  tt0000004             Un bon bock            6.1       NaN         NaN
4  tt0000005        Blacksmith Scene            6.2       NaN         NaN

In [13]:
df4.shape

(999999, 5)

In [14]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999999 entries, 0 to 999998
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   tconst         999999 non-null  object 
 1   title          999999 non-null  object 
 2   averageRating  445935 non-null  float64
 3   listed_in      11120 non-null   object 
 4   description    11120 non-null   object 
dtypes: float64(1), object(4)
memory usage: 45.8+ MB


In [15]:
df4.duplicated().sum() 

0

In [16]:
df4.isna().sum()

tconst                0
title                 0
averageRating    554064
listed_in        988879
description      988879
dtype: int64

In [17]:
df4.dropna(subset=["averageRating", "listed_in", 'description'], inplace=True)

In [18]:
df4.isna().sum()

tconst           0
title            0
averageRating    0
listed_in        0
description      0
dtype: int64

In [19]:
df4.shape

(7522, 5)

In [20]:
#df4.reset_index(inplace=True)

In [21]:
df4.head(5)

tconst                    title  averageRating  \
435   tt0000439  The Great Train Robbery            7.3   
483   tt0000487  The Great Train Robbery            7.0   
748   tt0000758          Sherlock Holmes            6.2   
958   tt0000969           Les Misérables            6.4   
1132  tt0001144                 The Call            4.8   

                                              listed_in  \
435   British TV Shows, Crime TV Shows, Internationa...   
483   British TV Shows, Crime TV Shows, Internationa...   
748                        Action & Adventure, Comedies   
958      Dramas, International Movies, Music & Musicals   
1132                    International Movies, Thrillers   

                                            description  
435   This two-part tale delivers the true story of ...  
483   This two-part tale delivers the true story of ...  
748   The game is afoot for an eccentric detective w...  
958   The musical version of Victor Hugo's epic tale...  
1132  Connected by phone in the same home but 20 yea...

In [22]:
df4.drop(columns=['tconst', 'listed_in'], inplace = True)
                        
                     

In [23]:
df4 = df4.reset_index(drop=True)
df4.head()

title  averageRating  \
0  The Great Train Robbery            7.3   
1  The Great Train Robbery            7.0   
2          Sherlock Holmes            6.2   
3           Les Misérables            6.4   
4                 The Call            4.8   

                                         description  
0  This two-part tale delivers the true story of ...  
1  This two-part tale delivers the true story of ...  
2  The game is afoot for an eccentric detective w...  
3  The musical version of Victor Hugo's epic tale...  
4  Connected by phone in the same home but 20 yea...

In [24]:
import nltk
#nltk.download()
import re

import pickle
nltk.download('stopwords')

from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer

ps= PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tddagdas/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [25]:
df4.head()

title  averageRating  \
0  The Great Train Robbery            7.3   
1  The Great Train Robbery            7.0   
2          Sherlock Holmes            6.2   
3           Les Misérables            6.4   
4                 The Call            4.8   

                                         description  
0  This two-part tale delivers the true story of ...  
1  This two-part tale delivers the true story of ...  
2  The game is afoot for an eccentric detective w...  
3  The musical version of Victor Hugo's epic tale...  
4  Connected by phone in the same home but 20 yea...

In [26]:
#df4.rename(columns={'description': 'text'}, inplace=True)

In [27]:
# Apply a first round of text cleaning techniques
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

round1 = lambda x: clean_text_round1(x)

In [28]:
# Let's take a look at the updated text
data_clean = pd.DataFrame(df4.description.apply(round1))
data_clean

description
0     this twopart tale delivers the true story of t...
1     this twopart tale delivers the true story of t...
2     the game is afoot for an eccentric detective w...
3     the musical version of victor hugos epic tale ...
4     connected by phone in the same home but  years...
...                                                 ...
7517  with humor and empathy brené brown discusses w...
7518  there is no such thing as an ordinary interact...
7519  embark on a global cultural journey into stree...
7520  forging his own comedic boundaries anthony jes...
7521  the only downside to a young couple’s new drea...

[7522 rows x 1 columns]

In [29]:
# Apply a second round of cleaning

def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = text.lower()
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    text = re.sub('[^a-zA-Z]', ' ', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [30]:
# Let's take a look at the second round
data_clean = pd.DataFrame(df4.description.apply(round2))
data_clean

description
0     this two part tale delivers the true story of ...
1     this two part tale delivers the true story of ...
2     the game is afoot for an eccentric detective w...
3     the musical version of victor hugo s epic tale...
4     connected by phone in the same home but    yea...
...                                                 ...
7517  with humor and empathy  bren  brown discusses ...
7518  there is no such thing as an ordinary interact...
7519  embark on a global cultural journey into stree...
7520  forging his own comedic boundaries  anthony je...
7521  the only downside to a young couples new dream...

[7522 rows x 1 columns]

In [31]:
# We are going to create a document-term matrix using CountVectorizer, and exclude common English stop words

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(data_clean.description)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = data_clean.index
data_dtm

aamir  aang  abagnale  abandoned  abandoning  abandonment  abbey  \
0         0     0         0          0           0            0      0   
1         0     0         0          0           0            0      0   
2         0     0         0          0           0            0      0   
3         0     0         0          0           0            0      0   
4         0     0         0          0           0            0      0   
...     ...   ...       ...        ...         ...          ...    ...   
7517      0     0         0          0           0            0      0   
7518      0     0         0          0           0            0      0   
7519      0     0         0          0           0            0      0   
7520      0     0         0          0           0            0      0   
7521      0     0         0          0           0            0      0   

      abbott  abdel  abduct  ...  zirkus  zodiac  zombie  zombies  zone  \
0          0      0       0  ...       0       0       0        0     0   
1          0      0       0  ...       0       0       0        0     0   
2          0      0       0  ...       0       0       0        0     0   
3          0      0       0  ...       0       0       0        0     0   
4          0      0       0  ...       0       0       0        0     0   
...      ...    ...     ...  ...     ...     ...     ...      ...   ...   
7517       0      0       0  ...       0       0       0        0     0   
7518       0      0       0  ...       0       0       0        0     0   
7519       0      0       0  ...       0       0       0        0     0   
7520       0      0       0  ...       0       0       0        0     0   
7521       0      0       0  ...       0       0       0        0     0   

      zordon  zorro  zoya  zozo  zulu  
0          0      0     0     0     0  
1          0      0     0     0     0  
2          0      0     0     0     0  
3          0      0     0     0     0  
4          0      0     0     0     0  
...      ...    ...   ...   ...   ...  
7517       0      0     0     0     0  
7518       0      0     0     0     0  
7519       0      0     0     0     0  
7520       0      0     0     0     0  
7521       0      0     0     0     0  

[7522 rows x 8593 columns]

In [32]:
df4['averageRating'].dtype

#int(num1)

dtype('float64')

In [33]:
df4['averageRating'] = df4['averageRating'].astype(int)

df4['averageRating'].dtype

dtype('int64')

In [34]:
df4['averageRating'].value_counts()

7     2561
6     2019
8     1317
5      936
4      374
3      139
9      128
2       42
1        3
10       3
Name: averageRating, dtype: int64

In [35]:
X= data_dtm
y= df4['averageRating']

In [36]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33)

In [37]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)
print('GNB')
print(cm)

GNB
[[  0   0   0   0   0   1   0   0   0   0]
 [  0   0   1   1   3   2   2   0   2   0]
 [  0   1   2   5  12   5   3   8   4   0]
 [  0   5   9  22  31  16  15  15  13   1]
 [  1  11  23  43  73  47  27  43  29   0]
 [  0  16  39  89 174 105  93 103  57   1]
 [  1  29  52  97 232 139  65 131  93   4]
 [  1  18  32  44 111  68  33  73  60   1]
 [  0   2   5   6  14   6   2   7   2   1]
 [  0   0   0   0   0   0   0   1   0   0]]
